# Generated by Django 5.2.17 on 2026-08-16 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_voiceprofile_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('company', models.CharField(blank=True, default='', max_length=128)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=32)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('need', models.TextField(blank=True, default='')),
                ('has_existing_website', models.BooleanField(blank=True, null=True)),
                ('website_action', models.CharField(blank=True, default='', max_length=32)),
                ('business_description', models.TextField(blank=True, default='')),
                ('start_timeline', models.CharField(blank=True, default='', max_length=128)),
                ('lead_intent', models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='', max_length=16)),
                ('appointment_time', models.CharField(blank=True, default='', max_length=128)),
                ('appointment_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='calls.callsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
